source/includes/_instruments.md
Added Issuing/Allocation API docs.
=> GJ-184 - Allocation API docs

source/includes/_isaadmin.md
=> GJ-231: Fix isa admin enums

source/includes/_payments.md
=> GJ-231: Fix payments enums

source/includes/_bonds.md
=> GJ-231: Fix bond-management enums

source/includes/_investors.md
Looks like transfer out response is missing. Its not in the swagger either
=> GJ-115: Add investor enums

source/index.html.md
- Rephrased some sections
- Broke out functionality of each endpoint for readability
- Fixed some missing closing statements for code examples
=> Readability updates to intro section

source/index.html.md
=> Fixed bullet point issues

source/index.html.md
=> Small typos fixed

source/includes/_quickstart-settlement.md
=> Moved order of code examples, some title changes, etc

source/layouts/layout.erb, source/stylesheets/_variables.scss, source/stylesheets/screen.css.scss
=> Tweak how the language selector looks and code samples

source/includes/_payments.md
Seems like some of those fields are not required and some we don't even use but this is the current state and until we change the annotations those fields are mandatory.
I've POSTed that json and it seems to be working.
This still need some major update but this version is better then what's currently deployed so shipping this.
=> Update the create corporate docs with current state of DTOs

source/includes/_investors.md, source/includes/_isaadmin.md, source/includes/_payments.md
Include array response docs from old Swagger docs
Also:
- And add closed transfer in endpoint
- Removed duplicate `/transactions` endpoint
- Added transaction status and type possible values
=> Pull array reponses from Swagger docs

source/includes/_trade-settlement.md
=> Correct code example syntax highlighting

source/stylesheets/screen.css.scss
=> Style search bar so it's a little bit more distinct from the TOC

source/includes/_payments.md
=> Fixed return body for withdrawal endpoint

source/includes/_payments.md
Endpoint to get balance of a wallet
=> wallet balances

source/includes/_investor-payments.md
endpoint for platform fee extraction
=> platform fee extraction endpoint

source/includes/_webhooks.md
adding webhook docs for TRADE_SETTLEMENT, DIVIDEND_UPDATE, BATCH_UPDATE events
=> GJ-399: adding docs for new webhooks

source/includes/_webhooks.md
=> Account fee webhook

source/includes/_bulk-payments.md
Adding documentation for test payment endpoint for bulk payments.
=> Adding test endpoint documentation.

source/includes/_bulk-payments.md
=> Correct formatting for the /test/account/topup endpoint

source/includes/_platform-payments.md
Remove `originatorId` from wallet DTO and add `bankDetails`
=> fixes the wallet DTO to not leak originatorId

source/includes/_platform-payments.md
Add wallet endpoint docs for new endpoints and clean up old docs.
=> GJ-296 fix and document wallet endpoints

source/includes/_bulk-payments.md, source/includes/_corporate-actions.md, source/includes/_investor-payments.md
X-GOJI-REQUEST-ID is a header added to the response not the request.
It looks confusing being on both request and response sample.
=> Remove confusing X-GOJI-REQUEST-ID from request samples

source/includes/_quickstart-wallets.md, source/index.html.md
Add a wallet quickstart guide to walk through the flow of adding a company, a wallet, registering some details and sending money from the wallet. Probably can be expanded upon but feels like a good starter for 10 :)
=> GJ-135 add wallets quickstart guide to explain the flow

source/includes/_platform-payments.md
=> Add response error codes to wallet payment instruction docs

source/includes/_quickstart-equities.md, source/includes/_quickstart-wallets.md, source/includes/_webhooks.md
Logically Company webhook will be first followed by Wallets webhooks.
Makes it easier to read and copy.
=> Move Company webhook to be right above Wallets webhooks

source/includes/_bulk-payments.md, source/includes/_webhooks.md
**REQUIREMENTS TO CANDIDATE:**
Native English speaker or at least advanced.
**OBLIGATIONS:**
Sanitize PR and maybe add a more detailed description if needed.
**BENEFITS:**
Respect.
=> Updated batch/dividend webhooks content to contains only payments summary

source/includes/_webhooks.md
PR with mirror changes in webhooks app https://github.com/Goji-P2P/webhooks-application/pull/127
=> Use clientId instead of investorId in ACCOUNT_FEE_PROCESSED hook

source/includes/_webhooks.md
Mirror PR in webhooks app https://github.com/Goji-P2P/webhooks-application/pull/128
=> Add client id to INVESTMENT_PAYOUT_EVENT webhook

source/includes/_webhooks.md
Not 100% sure on the wording. Suggestions? Updated to include notice boxes
=> GJ-617: Modify bank transfer event to include redirected info

source/includes/_quickstart-wallets.md
Adding a line to inform platforms that wallets are not available by default.
=> Adding notification that wallets are not available by default

source/includes/_platform-payments.md
Add `PUT /companies/{id}/enable` endpoint
Related PRs:
* api https://github.com/Goji-P2P/api-application/pull/497
* payments https://github.com/Goji-P2P/payments-application/pull/730
BEFORE:
AFTER:
=> GJ-693 Add endpoint to enable Company in sandbox

source/includes/_investors.md, source/includes/_isaadmin.md, source/includes/_quickstart-wallets.md, source/includes/platform-payments.md.erb, source/includes/quickstart-settlement.md.erb, source/partials/enabling_payment_destination_bank_account_details.erb
And a bunch of small cosmetic and consistency improvements here and there.
BEFORE:
AFTER:
=> Document endpoint to enable payment destination in test and sandbox

source/includes/_investor-assets.md, source/includes/_trade-settlement.md, source/index.html.md.erb
=> adding docs describing how to view investor assets. + clean up.

source/includes/platform-payments.md.erb
=> Document 409 response when creating wallet with existing name

source/includes/debt-settlement.md.erb
Secondary Market Sale With `repaymentReference` specified. Note: reference
```
{
"id": "c47e0169-fd0d-48d7-94f7-d54b2760b537",
"dateTime": "2020-07-22T08:47:19",
"type": "INVESTOR_FUNDS_RECEIVED",
"content": {
"clientId": "NONE-66557",
"reference": "Sale of Investment",
"amount": {
"amount": 0.9,
"currency": "GBP"
},
"sourceAccount": {
"accountName": "Humpty DumptyDAUSPU",
"accountNumber": "70242283",
"sortCode": "000000"
},
"accountType": "GOJI_INVESTMENT",
"intendedAccountType": null,
"redirected": false,
"sourceType": "CAPITAL_REPAYMENT"
}
}
```
Secondary Market Sale without `repaymentReference` specified
```
"id": "e251d49c-d04e-4185-971b-72a732465ae1",
"dateTime": "2020-07-22T08:49:19",
"type": "INVESTOR_FUNDS_RECEIVED",
"content": {
"clientId": "NONE-66557",
"reference": …
```
=> Reference updates to secondary markets and repayments

source/includes/_instruments.md
=> GJ-900: Added allocatio status to equity docs

source/includes/_bonds.md, source/includes/_instruments.md, source/includes/_quickstart-equities.md, source/includes/_quickstart-wallets.md, source/includes/investor-payments.md.erb, source/includes/platform-payments.md.erb, source/index.html.md.erb
=> feat: added doc for sole traders

source/includes/_isaadmin.md
Updates to the 'death of investor' process section.
=> [ITS-365] - Updates to 'Death of investor' section

source/includes/debt-settlement.md.erb
Remove duplicated warning message
=> remove duplicated warning ruining url nav

source/includes/_isaadmin.md
Updating the formatting on 'death of investor'
=> [ITS-365] - Formatting changes to 'Death of investor section'

source/includes/investor-payments.md.erb
Update to our API docs to:
- Update the withdrawal response to "SUCCESS"
- Remove the incorrect response body in the section for /withdrawal
=> [ITS-1466] - Update to /withdrawal endpoint documentation

source/includes/debt-settlement.md.erb
=> ✨ updated API docs for secondary market trade endpoint

source/includes/investor-payments.md.erb
Added: ![Screenshot 2022-06-14 at 15 17 35](https://user-images.githubusercontent.com/3105832/173600253-837d7671-df9a-4069-b0be-56cd5dc9e530.png)
=> Document default withdrawal payment reference

source/includes/debt-settlement.md.erb
Use accurate clientId in the response example.
=> GJ-4175 update response example

source/includes/debt-settlement.md.erb
Add a notice, that the INTEREST_CASH repayments feature is disabled.
=> GJ-4489 interest_cash repayments disabled

source/includes/_isaadmin.md, source/includes/debt-settlement.md.erb
update docs, so they support 'PREMIUM' repayments
=> GJ-4320 add premium type

docker-compose.yml, source/includes/investors.md.erb, source/includes/quickstart-settlement.md.erb, source/partials/kyc_vs_kyb.erb
For corporate Investors the `GET /kyb` endpoint should be used to retrieve it's KYX status.
=> Mention that for corporates use /kyb endpoint

.github/workflows/deply_docs.yml
It was so old it didn't compile anymore.
=> Fix GHA build and deploy

.github/workflows/deply_docs.yml, Dockerfile, docker-compose.yml, source/includes/_bulk-payments.md, source/includes/quickstart-settlement.md.erb
Also fix local docker setup as it was no longer working.
=> Explain how to deposit funds to test batch payments in sandbox

README.md, source/includes/_isaadmin.md, source/includes/investors.md.erb
=> GJ-8628 Deprecate `INVALID_TAX_YEAR_BREAK` references

source/includes/debt-settlement.md.erb
=> GJ-9512 Update `POST /platformApi/settlement/investor-repayment` docs

README.md, source/includes/_isaadmin.md, source/includes/investors.md.erb
=> GJ-9521 Clarify ISA Transfer In widget docs
